USE [oven]
GO

/****** Object:  Table [dbo].[FT08]    Script Date: 2/10/2026 2:50:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FT08](
	[Id] [uniqueidentifier] NOT NULL,
	[C000] [int] NULL,
	[C001] [nvarchar](max) NULL,
 CONSTRAINT [PK_FT08] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

